=== kvark/kri-web/deploy/schema/rast.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
		targetNamespace="http://www.kri.org/rast"
		xmlns:xs="http://www.w3.org/2001/XMLSchema"
		xmlns:this="http://www.kri.org/rast"
		elementFormDefault="qualified">

	<xs:annotation>
		<xs:documentation xml:lang="en">
		KriWeb rasterizer states definitions.
		</xs:documentation>
	</xs:annotation>
	
	<!-- Shared -->
	<xs:simpleType name="TFloatPositive">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0.0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TIntPositive">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TFace">
		<xs:restriction base="xs:string">
			<xs:enumeration value="front" />
			<xs:enumeration value="back" />
			<xs:enumeration value="all" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TFunction">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="TColor">
		<xs:attribute name="r" type="this:TFloatPositive" />
		<xs:attribute name="g" type="this:TFloatPositive" />
		<xs:attribute name="b" type="this:TFloatPositive" />
		<xs:attribute name="a" type="this:TFloatPositive" />
	</xs:complexType>

	<!-- Primitive -->
	<xs:complexType name="TPrimitive">
		<xs:attribute name="front">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="cw" />
					<xs:enumeration value="ccw" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="cull" type="this:TFace" />
		<xs:attribute name="lineWidth" type="this:TFloatPositive" />
	</xs:complexType>

	<!-- Offset -->
	<xs:complexType name="TOffset">
		<xs:attribute name="factor"	type="xs:float" />
		<xs:attribute name="units"	type="xs:float" />
	</xs:complexType>
	
	<!--Scissor -->
	<xs:complexType name="TScissor">
		<xs:attribute name="x" type="this:TIntPositive" />
		<xs:attribute name="y" type="this:TIntPositive" />
		<xs:attribute name="w" type="this:TIntPositive" />
		<xs:attribute name="h" type="this:TIntPositive" />
	</xs:complexType>
	
	<!--MultiSample -->
	<xs:complexType name="TMultiSample">
	</xs:complexType>

	<!-- Stencil -->
	<xs:simpleType name="TOperation">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="TStencilChannel">
		<xs:sequence>
			<xs:element name="Test">
				<xs:complexType>
					<xs:attribute name="func"	type="this:TFunction" />
					<xs:attribute name="ref"	type="xs:int" />
					<xs:attribute name="mask"	type="xs:int" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Operation" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="fail"		type="this:TOperation" />
					<xs:attribute name="depthFail"	type="this:TOperation" />
					<xs:attribute name="pass"		type="this:TOperation" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="face" type="this:TFace" />
	</xs:complexType>
	
	<xs:complexType name="TStencil">
		<xs:sequence>
			<xs:element name="Channel" type="this:TStencilChannel" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Depth -->
	<xs:complexType name="TDepth">
		<xs:attribute name="func" type="this:TFunction" />
	</xs:complexType>
	
	<!-- Blend -->
	<xs:simpleType name="TBlendArea">
		<xs:restriction base="xs:string">
			<xs:enumeration value="color" />
			<xs:enumeration value="alpha" />
			<xs:enumeration value="both" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="TBlendEquation">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TBlendFactor">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="TBlendChannel">
		<xs:attribute name="on"				type="this:TBlendArea" />
		<xs:attribute name="equation"		type="this:TBlendEquation" />
		<xs:attribute name="source"			type="this:TBlendFactor" />
		<xs:attribute name="destination"	type="this:TBlendFactor" />
	</xs:complexType>
	
	<xs:complexType name="TBlend">
		<xs:sequence>
			<xs:element name="Channel"	type="this:TBlendChannel" maxOccurs="2" />
			<xs:element name="Ref"		type="this:TColor" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<!-- Mask -->
	<xs:simpleType name="TMaskColor">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="TMask">
		<xs:attribute name="stencilFront"	type="xs:int" />
		<xs:attribute name="stencilBack"	type="xs:int" />
		<xs:attribute name="depth"			type="xs:boolean" />
		<xs:attribute name="color"			type="this:TMaskColor" />
	</xs:complexType>
	
	<!-- Rasterizer -->
	<xs:complexType name="TRast">
		<xs:all>
			<xs:element name="Primitive"	type="this:TPrimitive"		minOccurs="0" />
			<xs:element name="Offset"		type="this:TOffset"			minOccurs="0" />
			<xs:element name="Scissor"		type="this:TScissor"		minOccurs="0" />
			<xs:element name="MultiSample"	type="this:TMultiSample"	minOccurs="0" />
			<xs:element name="Stencil"		type="this:TStencil"		minOccurs="0" />
			<xs:element name="Depth"		type="this:TDepth"			minOccurs="0" />
			<xs:element name="Blend"		type="this:TBlend"			minOccurs="0" />
			<xs:element name="Mask"			type="this:TMask"			minOccurs="0" />
		</xs:all>
	</xs:complexType>
	
	<xs:element name="Rast" type="this:TRast" />

</xs:schema>

=== kvark/kri-web/deploy/schema/test.xml
<?xml version="1.0"?>
<kri:Rast
		xmlns:kri="http://www.kri.org/rast"
		xmlns:kw="http://www.kri.org/world"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="
			rast.xsd
			world.xsd">

	<kri:Primitive front="ccw" cull="back" lineWidth="0.5" />
	<kri:Offset units="0.4" factor="1.0" />
	<kri:Scissor x="0" y="0" w="100" h="100" />
	<kri:MultiSample alpha="true">
		<kri:Coverage value="2" invert="false" />
	</kri:MultiSample>
	<kri:Stencil>
		<kri:Channel face="all">
			<kri:Test func="==" ref="1" mask="3" />
			<kri:Operation fail="" depthFail="+" pass="~" />
		</kri:Channel>
	</kri:Stencil>
	<kri:Depth func="&lt;=" />
	<kri:Blend>
		<kri:Channel on="color" equation="d-s" source="Sa" destination="Cc"/>
		<kri:Channel on="alpha" equation="s+d" source="Sc" destination="1" />
		<kri:Ref r="0.4" g="0.3" b="0.2" a="0.1" />
	</kri:Blend>
	<kri:Mask stencilFront="-1" stencilBack="-2" depth="true" color="RGB" />
</kri:Rast>
